version: '3.8'

services:

  almacenamiento:
    build: ./almacenamiento
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${MONGO_DB}?retryWrites=true&w=majority&tls=true&authSource=admin
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_CLUSTER=${MONGO_CLUSTER}
      - MONGO_DB=${MONGO_DB}
      - MONGO_COLLECTION=${MONGO_COLLECTION}

  scraper:
    build:
      context: ./scraper
    environment:
      - URL_ALMACENAMIENTO=http://almacenamiento:8000/eventos
    depends_on:
      - almacenamiento

  filtrador:
    build: ./filtrador
    depends_on:
      - almacenamiento
    env_file:
      - .env
    volumes:
      - ./filtrador/outputs:/app/outputs
    command: python filtrador.py


  procesador:
    image: bde2020/pig
    volumes:
      - ./procesador:/data
    command: pig /data/analisis.pig
    depends_on:
      - filtrador

volumes: {}
