version: '3.8'

services:

  redis:                                        #LRU y LFU
    image: redis:latest               # descomentar y comentar la otra para cambiar la politica:
    command: redis-server --maxmemory 10gb --maxmemory-policy allkeys-lru # allkeys-lfu
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  cache:
    build: ./cache
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - almacenamiento
    environment:
    - TTL_CACHE=86400
  

  almacenamiento:
    build: ./almacenamiento
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${MONGO_DB}?retryWrites=true&w=majority&tls=true&authSource=admin
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_CLUSTER=${MONGO_CLUSTER}
      - MONGO_DB=${MONGO_DB}
      - MONGO_COLLECTION=${MONGO_COLLECTION}

  scraper:
    build:
      context: ./scraper
    environment:
      - URL_ALMACENAMIENTO=http://almacenamiento:8000/eventos
    depends_on:
      - almacenamiento

  filtrador:
    build: ./filtrador
    depends_on:
      - almacenamiento
    env_file:
      - .env
    volumes:
      - ./filtrador/outputs:/app/outputs
    command: python filtrador.py


  procesador:
    image: bde2020/pig
    volumes:
      - ./procesador:/data
    command: pig /data/analisis.pig
    depends_on:
      - filtrador

volumes:
  # mongodb_data:
  redis_data: