
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    

  almacenamiento:
    build: ./almacenamiento
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  cache:
    build: ./cache
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - almacenamiento

volumes:
  mongodb_data:
  redis_data: