
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    

  almacenamiento:
    build: ./almacenamiento
    volumes:
    - ./almacenamiento/app:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  cache:
    build: ./cache
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - almacenamiento
  
  generador:
    build: ./generador_trafico

    volumes:
      - ./generador_trafico/app:/app
    environment:
      - PYTHONUNBUFFERED=1  # Para ver logs inmediatos
      - DEBUG=True          # Variable para modo desarrollo
    command: > 
      sh -c "echo '▶ Iniciando generador (modo desarrollo)...' && 
      while true; do 
        python main.py || echo '⚡ Error: Reiniciando...'; 
        sleep 1; 
      done"
    # ports:
    #   - "9000:9000"
    depends_on:
      - almacenamiento
      - cache 


volumes:
  mongodb_data:
  redis_data: